"conda uninstall enum34" to fix Travis CI error
Travis CI said: https://travis-ci.org/simonw/csvs-to-sqlite/jobs/304049103

    $ conda install --yes python=$TRAVIS_PYTHON_VERSION numpy pandas
    Fetching package metadata ...........
    Solving package specifications: .
    UnsatisfiableError: The following specifications were found to be in conflict:
      - enum34 -> python 2.7*
      - python 3.6*
    Use "conda info <package>" to see the dependencies for each package.

Using suggested fix from https://stackoverflow.com/a/42075651/6083